#Numpy
NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.The array object in NumPy is called ndarray.
We can create a NumPy ndarray object by using the array() function.
Ctrl+Enter to run • Shift+Enter for next

In [11]:
import numpy
arr = numpy.array([1, 2, 3, 4, 5])
print(arr)
#type of array
print(type(arr))
print(numpy.__version__)
#Rank/dimension of an Array
print(arr.ndim)
#shape of an Array
print(arr.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
2.2.5
1
(5,)


In [12]:
## We create a rank 1 ndarray of floats but set the dtype to int64
import numpy asnp
x = np.array([1.5, 2.2, 3.7, 4.0, 5.9], dtype = np.int64)

## We print the dtype x
print('x = ', x)
print('The elements in x are of type:', x.dtype)

x =  [1 2 3 4 5]
The elements in x are of type: int64


numpy.ndarray.size and Creating a 2-D array.
We create a rank 2 ndarray that only contains integers.

In [19]:
Y = np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])

print('Y = \n', Y)

## We print information about Y
print('Y has dimensions:', Y.shape)
print(f'Y has a total of {Y.size} elements')
print('Y is an object of type:', type(Y))
print('The elements in Y are of type:', Y.dtype)

Y = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Y has dimensions: (4, 3)
Y has a total of 12 elements
Y is an object of type: <class 'numpy.ndarray'>
The elements in Y are of type: int32


In [22]:
#Save the NumPy array to a File
x = np.array([1, 2, 3, 4, 5])
## We save x into the current directory as 
np.save('my_array', x)

In [26]:
# We create a 3 x 4 ndarray full of zeros. 
X = np.zeros((3,4))
print('X = \n', X)
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)

X = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
X has dimensions: (3, 4)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


In [27]:
# We create a 3 x 2 ndarray full of ones. 
X = np.ones((3,2))
print('X = \n', X)
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)

X = 
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
X has dimensions: (3, 2)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


In [29]:
#Create a Numpy array of constants
# We create a 2 x 3 ndarray full of fives. 
X = np.full((2,3), 5)
print('X = \n', X)
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)

X = 
 [[5 5 5]
 [5 5 5]]
X has dimensions: (2, 3)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: int32


In [30]:
# We create a 5 x 5 Identity matrix. 
X = np.eye(5)
print('X = \n', X)
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)

X = 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
X has dimensions: (5, 5)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


In [31]:
# Create a 4 x 4 diagonal matrix that contains the numbers 10,20,30, and 50
# on its main diagonal
X = np.diag([10,20,30,50])
print('X = \n', X)
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)

X = 
 [[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 50]]
X has dimensions: (4, 4)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: int32


numpy.arange
Syntax:
numpy.arange([start, ]stop, [step, ]dtype=None)

It returns evenly spaced values within a given interval.

In [35]:
# We create a rank 1 ndarray that has sequential integers from 0 to 9
X = np.arange(10)
print('X =', X)
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)
print()
# We create a rank 1 ndarray that has sequential integers from 4 to 9. 
Y = np.arange(4,10)
print('Y =', Y)
print('Y has dimensions:',Y.shape)
print('Y is an object of type:', type(Y))
print('The elements in Y are of type:', Y.dtype)
print()
# We create a rank 1 ndarray that has evenly spaced integers from 1 to 13 in steps of 3.
Z = np.arange(1,14,3)
print('Z =', Z)
print('Z has dimensions:', Z.shape)
print('Z is an object of type:', type(Z))
print('The elements in Z are of type:', Z.dtype)

X = [0 1 2 3 4 5 6 7 8 9]
X has dimensions: (10,)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: int32

Y = [4 5 6 7 8 9]
Y has dimensions: (6,)
Y is an object of type: <class 'numpy.ndarray'>
The elements in Y are of type: int32

Z = [ 1  4  7 10 13]
Z has dimensions: (5,)
Z is an object of type: <class 'numpy.ndarray'>
The elements in Z are of type: int32


Create a Numpy array using linspace(start, stop, n), with stop inclusive and exclusive.
the function np.linspace(0,25,10) returns an ndarray with 10 evenly spaced numbers in the closed interval [0, 25]

In [36]:
# We create a rank 1 ndarray that has 10 integers evenly spaced between 0 and 25.
X = np.linspace(0,25,10)
print('X =', X)

# We create a rank 1 ndarray that has 10 integers evenly spaced between 0 and 25,
# with 25 excluded.
Y = np.linspace(0,25,10, endpoint = False)
print('Y =', Y)

X = [ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]
Y = [ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]


numpy.reshape - This is a Function.
Syntax:

numpy.reshape(array, newshape, order='C')[source]

It gives a new shape to an array without changing its data.

In [49]:
# We create a rank 1 ndarray with sequential integers from 0 to 19
x = np.arange(20)
print('Original x = ', x)

# We reshape x into a 4 x 5 ndarray 
x = np.reshape(x, (4,5))

print('Reshaped x = \n', x)
print('x has dimensions:', x.shape)

# We create a a rank 1 ndarray with sequential integers from 0 to 19 and
# reshape it to a 4 x 5 array 
Y = np.arange(25).reshape(5, 5)
print('Y = \n', Y)

# We create a rank 1 ndarray with 10 integers evenly spaced between 0 and 50,
# with 50 excluded. We then reshape it to a 5 x 2 ndarray
Z = np.linspace(0,50,10, endpoint=False).reshape(5,2)
print('Z= \n',Z)

Original x =  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Reshaped x = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
x has dimensions: (4, 5)
Y = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Z= 
 [[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]]


Create a Numpy array using the numpy.random.random() function.

In [53]:
# We create a 3 x 3 ndarray with random floats in the half-open interval [0.0, 1.0).
X = np.random.random((3,3))
print('X=\n',X)
print('\n')

# We create a 3 x 2 ndarray with random integers in the half-open interval [4, 15).
Y = np.random.randint(4,15,size=(3,2))
print('Y=\n',Y)
print('\n')

# We create a 1000 x 1000 ndarray of random floats drawn from normal (Gaussian) distribution
# with a mean of zero and a standard deviation of 0.1.
Z = np.random.normal(0, 0.1, size=(1000,1000))
print('Z=\n',Z)






X=
 [[0.81464299 0.44060914 0.19369126]
 [0.12386775 0.46371163 0.6271252 ]
 [0.37160898 0.9408434  0.32908366]]


Y=
 [[ 8  7]
 [ 9  4]
 [14  5]]


Z=
 [[ 0.07211216 -0.14720388 -0.00388925 ... -0.06413218  0.11882867
   0.10109497]
 [ 0.14495705 -0.03030666  0.17304476 ...  0.01210038 -0.05283197
  -0.14006258]
 [ 0.03330386 -0.10626366 -0.06272309 ...  0.06102483  0.08792235
   0.0185089 ]
 ...
 [-0.18890946  0.00243774 -0.0656573  ... -0.044101   -0.00116148
  -0.06600318]
 [ 0.02456519  0.04805222 -0.14882356 ... -0.0292034  -0.01019157
   0.06899698]
 [ 0.05390854  0.01369593 -0.05961093 ...  0.05327418  0.06115013
  -0.10432458]]
